pipeline {
    agent any

    parameters {
        string(name: 'url', defaultValue: 'https://swapi.dev/api', description: 'Base URL for testing')
        string(name: 'suiteName', defaultValue: 'FilmSuite.xml', description: 'Test Suite')
    }

    tools {
        maven "M3"
    }

    stages {
        stage('Clone and Fetch') {
            steps {
                script {
                    // Clone and fetch steps
                    git branch: 'main', url: 'https://github.com/BryanGaray99/ci_cd_practice.git'
                }
            }
        }

        stage('Compile') {
            steps {
                script {
                    bat "mvn -B -DskipTests clean package"
                }
            }
        }

        stage('Execute Tests') {
            steps {
                script {
                    // Run the test suite
                    bat "mvn test -Durl=${params.url} -DsuiteFile=${params.suiteName}"
                }
            }
            post {
                always{
                    allure([
                    includeProperties: false,
                    jdk: '',
                    properties: [],
                    reportBuildPolicy: 'ALWAYS',
                    results: [[path: '*/allure-results']]
                    ])
                }
            }
        }
    }
}